"""AUTH_SECRET handling and AES-256-GCM secret-at-rest encryption."""
import stat

import pytest

from app.config import settings
from app.services import secret_box


@pytest.fixture()
def box_env(tmp_path, monkeypatch):
    monkeypatch.setattr(settings, "storage_path", tmp_path)
    monkeypatch.setattr(settings, "auth_secret", None)
    monkeypatch.setattr(settings, "auth_secret_previous", None)
    return tmp_path


def test_auth_secret_autogenerated_with_0600(box_env):
    secret = secret_box.get_auth_secret()
    path = box_env / "auth_secret"
    assert path.exists()
    assert path.read_text().strip() == secret
    assert stat.S_IMODE(path.stat().st_mode) == 0o600
    # stable across calls
    assert secret_box.get_auth_secret() == secret


def test_env_auth_secret_wins_over_file(box_env, monkeypatch):
    (box_env / "auth_secret").write_text("file-secret")
    monkeypatch.setattr(settings, "auth_secret", "env-secret")
    assert secret_box.get_auth_secret() == "env-secret"


def test_encrypt_roundtrip(box_env):
    token = secret_box.encrypt(b"totp secret bytes")
    assert token.startswith("enc$v1$")
    plaintext, needs_reencrypt = secret_box.decrypt(token)
    assert plaintext == b"totp secret bytes"
    assert not needs_reencrypt


def test_encryption_is_nondeterministic(box_env):
    assert secret_box.encrypt(b"x") != secret_box.encrypt(b"x")


def test_tampered_ciphertext_rejected(box_env):
    token = secret_box.encrypt(b"payload")
    head, _, tail = token.rpartition("$")
    mangled = head + "$" + ("A" * len(tail))
    with pytest.raises(secret_box.DecryptionError):
        secret_box.decrypt(mangled)


def test_rotation_decrypts_under_previous_and_flags_reencrypt(box_env, monkeypatch):
    monkeypatch.setattr(settings, "auth_secret", "old-secret")
    token = secret_box.encrypt(b"payload")

    monkeypatch.setattr(settings, "auth_secret", "new-secret")
    with pytest.raises(secret_box.DecryptionError):
        secret_box.decrypt(token)

    monkeypatch.setattr(settings, "auth_secret_previous", "old-secret")
    plaintext, needs_reencrypt = secret_box.decrypt(token)
    assert plaintext == b"payload"
    assert needs_reencrypt

    # lazy re-encrypt: fresh token under the new secret decrypts cleanly
    fresh = secret_box.encrypt(plaintext)
    assert secret_box.decrypt(fresh) == (b"payload", False)


def test_unknown_format_rejected(box_env):
    with pytest.raises(secret_box.DecryptionError):
        secret_box.decrypt("plaintextsecret")
    with pytest.raises(secret_box.DecryptionError):
        secret_box.decrypt("enc$v2$AAAA$AAAA")
